### ISSUE TITLE
Firefox does not support "incognito": "split"

### ISSUE THREAD

**Issue by Semro** [Semro/syncwatch#10]
Added "incognito": "split" only in Chrome and Opera versions. Issue #9

**Comment by CanYouJustWorkPlease** [comment]
For Firefox it works out of the box the way it is, just gotta enable Sync Watch to run in Private mode. I just tested it out.

**Comment by Semro** [comment]
I have this error, loading it as a temporary add-on.
![image](https://user-images.githubusercontent.com/3332159/97776379-794c4880-1b78-11eb-9a73-f96454652aca.png)
And it's mentioned in MDN that split setting is not supported by Firefox: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito

**Comment by CanYouJustWorkPlease** [comment]
What I meant to say is the Sync Watch Firefox addon works fine for both normal mode and private mode, without having to add something like we added to Chrome, like "incognito": "split".
So Sync Watch version 0.324 Firefox addon works well for both modes already.

Isn't version 0.324 working fine for you, for both modes, in Firefox?

**Comment by CanYouJustWorkPlease** [comment]
Oh, Firefox also has "incognito": "split", I didn't know about that. But version 0.324 works fine without it, I don't know why, but it works.

**Comment by Semro** [comment]
Yes, Firefox working fine with 0.324 version.
Now I need to split manifest file between Chrome and Firefox. So, I just keep that issue open as a reminder.

**Comment by Semro** [comment]
Now manifest splitting in [CI workflow](https://github.com/Semro/syncwatch/commit/0a10207bb10ef16fcbaa9e6bdb0c9e3490872284#diff-71cabc4177e41ea8f15a89eb65398fa8187739f68a2762706d84885cd8b2ddc3R14-R19)
It removes "incognito": "split", line for Firefox manifest.
