### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by fabianski7** [Semro/syncwatch#12]
I could see in a recent commit that the extension now allows you to use another synchronization server in addition to what you maintain. And since it's in heroku, it might be a good idea to allow users to deploy their own instance through it as well, just as other projects allow this operation just by clicking on a link to do so.

**Comment by Semro** [comment]
"just as other projects allow this operation just by clicking on a link to do so"

can you provide more info on this?

**Comment by fabianski7** [comment]
https://github.com/xyu/heroku-wp#spin-up-a-demo
https://github.com/ohmyform/ohmyform#ohmyform
https://github.com/cagataycali/url-shortener

**Comment by Semro** [comment]
and Heroku's documentation about that: https://devcenter.heroku.com/articles/heroku-button
Maybe it's comfortable to deploy it first time, unfortunately, automatic updates with the original repository are not configurable and requires manual steps: https://medium.com/@JoeDuncko/how-to-update-a-heroku-app-installed-using-a-deploy-to-heroku-button-616ad5c6eea3

**Comment by fabianski7** [comment]
I understand.
Should I close this issue?

**Comment by Semro** [comment]
I would keep it open, maybe will resolve it someday.

**Comment by Semro** [comment]
Server is not hosted on Heroku anymore.
But we have Dockerfile, so you can spin it in VM: https://github.com/Semro/syncwatch/blob/master/packages/syncwatch-server/Dockerfile
