### ISSUE TITLE
CORS issues lately

### ISSUE THREAD

**Issue by WolfspiritM** [Semro/syncwatch#16]
Hi,

With Chromium Edge lately there has been a CORS issue when connecting to sync.herokuapp.
I think it has to do with the bump of socket io as it introduced "cors: false".

Also the URL set via the options window doesn't work as it's not being used. Not sure why.
So I had to do a workaround to self host but with cors: true connection works as expected.

**Comment by Semro** [comment]
Please reopen if it's still reproducible
