### ISSUE TITLE
CMD closes itself 

### ISSUE THREAD

**Issue by easymoney322** [Semro/syncwatch#19]
It just closes itself. There is no log neither in Window's Appdata\Local\CrashDumps, Window's event log, nor in project's folder.

I'm having some strange problems with the Internet lately: Sometimes I'm receiving timeouts while trying to connect and it continues for like 10 seconds or so. But here's the thing: Sometimes, when I get these connection timeout errors while trying to surf the net in the background, syncwatch still works. It crashes very rarely.

I'm not sure how timeouts would affect syncwatch tho, cause it probably can work even without the Internet, I didn't read the code tho. It's not the common out-of-ram error either, since I'm having pagefile and RAM usage not close to its limit

Not sure what version I'm using ATM, I've downloaded it on April 19th, but it looks like there were no updates since then so I'm assuming it's the last one

**Comment by easymoney322** [comment]
Also, after the re-launch of the server, it needs browser extension to be restarted, cause it can't connect to the IP. Not sure what it was saying, probably stucks at something like "Connecting...". Not a big deal, but still, I'm sure it can be fixed by setting a simple timelimit of connection try or something

**Comment by Semro** [comment]
> It just closes itself. There is no log neither in Window's Appdata\Local\CrashDumps, Window's event log, nor in project's folder.

Added logging errors to file
> I'm having some strange problems with the Internet lately: Sometimes I'm receiving timeouts while trying to connect and it continues for like 10 seconds or so. But here's the thing: Sometimes, when I get these connection timeout errors while trying to surf the net in the background, syncwatch still works. It crashes very rarely.

There is a "waking-up server" function in server code that is making HTTP requests to the server itself. The syncevent.herokuapp.com URL is hardcoded, so when it can't make a request the server falls down with exception. I changed it to run only in the Heroku environment.

**Comment by Semro** [comment]
@easymoney322 does it help you?

**Comment by easymoney322** [comment]
The connection itself got more stable, so I guess needs more time to see if it fixes the problem or not.
I will try to lower the quality of the connection just to check if it works, but it will take few more days.

However, since the new version, sometimes, when I launch the server, it looks like it doesn't start.  I think it might be also related to the problem I've had before. It doesn't output "Listening on ..." in cmd as well. The "Error.log" file is empty. 
It's not a big deal, since It takes exactly 1 second to re-launch it, but it's a bit annoying.

**Comment by Semro** [comment]
I've improved handling errors.
> However, since the new version, sometimes, when I launch the server, it looks like it doesn't start. I think it might be also related to the problem I've had before. It doesn't output "Listening on ..." in cmd as well. The "Error.log" file is empty.
It's not a big deal, since It takes exactly 1 second to re-launch it, but it's a bit annoying.

Maybe port already in use? Server using 8080 by default.

**Comment by easymoney322** [comment]
> Maybe port already in use? Server using 8080 by default.

I'm using 7777 port. It's very unlikely something running on it. Just had it and it took ~30 seconds before I've got "Listening on" message.  It's not a problem tho, since it just takes some extra time and everything works fine after.


So far no problems

**Comment by easymoney322** [comment]
Everything works just fine.
Even multiple lag-spikes with a latency of 42100 ms haven't caused any problems.
I think that the issue is solved.
