### ISSUE TITLE
Make it work on mobile device

### ISSUE THREAD

**Issue by vitonsky** [Semro/syncwatch#24]
Hi, thank you for best solution for co-watching the movies and videos.

Please, make it work on mobile devices. Check how it work on firefox nightly - popup is ugly and users cannot connect to server.
I sure that fix is not too hard for you. Also i hope that you don't given up development of this extension

**Comment by Semro** [comment]
Look into PR for details.
As another solution would be to use Yandex browser that supports Google Chrome extensions on mobile.

**Comment by vitonsky** [comment]
Why you need to open tab to extension will work?

**Comment by vitonsky** [comment]
I got you. Is it fixed now? Can we now use syncwatch on mobile firefox nightly?

**Comment by Semro** [comment]
Yes, it should work.
