### ISSUE TITLE
create a chat to chat with your friends while enjoying shared content

### ISSUE THREAD

**Issue by srpino23** [Semro/syncwatch#28]
a chat that appears to the right of the page where the video, movie, series, etc. is shared would be great and very comfortable something in the style of teleparty

![2-Teleparty](https://user-images.githubusercontent.com/63370189/161408442-8836be29-f5f6-4200-a5a3-ced98d055848.png)

**Comment by Semro** [comment]
Duplicate https://github.com/Semro/syncwatch/issues/5
