### ISSUE TITLE
[Research] Sync audio player

### ISSUE THREAD

**Issue by vitonsky** [Semro/syncwatch#31]
Hi, how you think, is possible to sync playing of audio players?

Right now i play my music on spotify and i think "if i would can listen music with my friends... right now, right here, just by press some button". But spotify, probably, use Audio object which is not append in DOM, so we can't access to player and can't manipulate on it.

I found this hack https://stackoverflow.com/questions/41514612/detect-audio-element-not-added-to-dom but i can't check work it or not, because we have to patch objects before load JS, and maybe in case with spotify, patch something for worker. But we can execute code on this stage with browser extensions API. Could you research this ability? If we could handle Audio even for spotify, then we can ensure correct work of sync an audio and can implement this feature. It would very cool

**Comment by Semro** [comment]
Doesn't Spotify has their own feature to sync audio between users? As I remember, it was available in integration with Discord.
It's actually would be cool (I'm thinking of [Soundcloud](https://soundcloud.com/)).
But I probably don't want to dig into that on my own. For now, it's obviously out of scope of this extension.
Thinking if an average track is ~4 minutes then in current implementation it would be annoying opening a new tab each next track, so it's would be reasonable implementing API for playlists https://github.com/Semro/syncwatch/issues/30. I think it will require a complete overhaul, which I'm not planning right now.
