### ISSUE TITLE
Not syncronize any more

### ISSUE THREAD

**Issue by RioChndr** [Semro/syncwatch#34]
This plugin are not syncronize or my connection is not normal, i don't know. Other people cannot play/pause/seek automatic. but status is connected

![image](https://user-images.githubusercontent.com/22429169/176991528-b9b3e862-4681-44b1-a5ff-0c7b0d82d054.png)

**Comment by Semro** [comment]
Try testing it on https://www.w3.org/2010/05/video/mediaevents.html

1. Make sure you have selected the tab with a video and pressed "share video" button.
2. There is a common problem with ad blocker extensions (AdBlock, AdGuard, uBlock Origin). Everyone in the room should disable it or everyone can enable it if all using same ad blocker.

If non-above helped, please provide:
- Browser details
- URL with a video

**Comment by RioChndr** [comment]
Nice, thank you for replying. I tried to disable adBlocker, and it works perfectly. Thank you so much

**Comment by RioChndr** [comment]
But for netflix not work.
browser mozilla 102.0 (64-bit), and chrome Version 103.0.5060.66

**Comment by Semro** [comment]
I don't have Netflix to test it by myself. Support was added by other contributor in https://github.com/Semro/syncwatch/pull/21. It uses Netflix API, so maybe it was outdated.
@nilshellerhoff if you're still interested in the extension, can you look into this? Much appreciated.

**Comment by nilshellerhoff** [comment]
Hi @RioChndr , hi @Semro ,

In my quick tests it still seems to work on my side with Netflix. I tested on one PC with Chrome 103.0.5060.66, Edge, 103.0.1264.44 and Firefox 102.0 side-by-side. If I have time tomorrow I will try two different PCs. @RioChndr can you try to test the plugin with a different browser than Firefox and see if the issue persists?

Thanks

**Comment by nilshellerhoff** [comment]
Hi @RioChndr , hi @Semro ,

I tested the plugin on Netflix and can indeed confirm that the newest version from `master` does not work. Using the version 0.400 from 743a84be55afe96cfdd3668129d707ece2f293c8 though seems to work as expected, also the API example in https://github.com/Semro/syncwatch/issues/20 works just fine.

I will try to see in the next days, what might have caused this issue.

Best
