### ISSUE TITLE
Self hosting configuration

### ISSUE THREAD

**Issue by mayankwadhwani** [Semro/syncwatch#36]
Hi - can you provide the heroku configuration used to run the server ? Further if we wish to run this on local LAN - will there be any change required in the server js ?

**Comment by Semro** [comment]
Hi.
In Heroku I have config var `HEROKU=true`, it enabels pinging server itself (so server will not sleep if its free dyno) , but address hardcoded here https://github.com/Semro/syncwatch/blob/2aa16e42a5bbda122dbfdf1bb133da709aea442e/server.js#L53, so you might change it, or better to pull it out in environment variable as well. 
To run server locally, executing command `npm run start` should be enough.

**Comment by mayankwadhwani** [comment]
Hi Semro. I hope you are doing good. so, you're saying that I can self host it on a rpi ? i can provide the IP address here ?

**Comment by mayankwadhwani** [comment]
Read through the code. Verified  the wakeserver actually works when working on heroku. I am running the server on a raspberry pi - running on IP 192.168.29.101 and the server runs at port 8080 . I entered http://192.168.29.101:8080, http://192.168.29.101 in the extension - but always get connection errors. Any suggestions on this @Semro ?

**Comment by mayankwadhwani** [comment]
@Semro - Yes - I am able to open the url in the browser. but the extension is not able to connect to the server. It says connection error.

**Comment by mayankwadhwani** [comment]
![Screenshot from 2022-11-03 00-57-01](https://user-images.githubusercontent.com/30961365/199584146-5d8fc039-b98e-40d2-b66d-df02c8856c95.png)

**Comment by mayankwadhwani** [comment]
Disabling and re-enabling the extension made it work. Thanks @Semro for the help here on selfhosting config.
