### ISSUE TITLE
Sync playbackRate between users

### ISSUE THREAD

**Issue by apmforgitissues012** [Semro/syncwatch#37]
Hello, thank you for maintaining this extension.
I prefer to watch videos at higher speeds, It would be convenient if the current video speed was synchronized between users.

The speed is normally stored in "document.querySelector('video').playbackRate"  
Implementing this features should be as easy as watching for a change and then setting the other client to the same speed.

Thank you for your time.

**Comment by apmforgitissues012** [comment]
Appologies, I see you're setting the plackbackRate here: https://github.com/Semro/syncwatch/blob/master/plugin/js/content.js#L144-L148

This seems to work as long as the playback rate is set through the video player's ui, If an extension like [Global Speed](https://github.com/polywock/globalSpeed) is used than the rate does not sync. 
Idealy, one client would have global speed disabled, and the other would overide the speed.

**Comment by Semro** [comment]
Fixed in https://github.com/Semro/syncwatch/commit/597b158061f1736cac20a20e6c0660a4633bd56f
