### ISSUE TITLE
BUG: Doesn't allow to toggle between "screen" and "lecture" on Harvard CS50 video player

### ISSUE THREAD

**Issue by sepsol** [Semro/syncwatch#41]
## Steps to reproduce:
1. Go here: https://cs50.harvard.edu/x/2023/weeks/5/
2. Play the video and try the `Screen` toggle at the top right of the player
3. Now, create a room and share the page
4. See how the `Screen` stops working

**Comment by Semro** [comment]
I don't think it's a bug. That's how the player works on this site.
When User1 toggles the screen, then the video player fires "pause" and then dispatches "seek" events each 500ms, extension handles it and sends to other users in the room.
![image](https://user-images.githubusercontent.com/3332159/214920109-6e9878a2-d908-47d8-b940-b957fe8200f3.png)

**Comment by sepsol** [comment]
I think you're right, it works if I just open the player in full screen.
