### ISSUE TITLE
fix: drop url strict comparison

### ISSUE THREAD

**Issue by jstsmthrgk** [Semro/syncwatch#47]
Currently https://media.ccc.de does not work, this is because the player changes the fragement part of the url (the part after #) whenever it gets paused. It would be nice if the fragment part of the url would just be ignored for media.ccc.de (or possibly all the time? I don't know which is better...)

**Comment by Semro** [comment]
It would be great to drop strict URL comparison at all.
We can depend on `tab.id`, but we should stop sync if user goes to a new URL in syncing tab.
Probably requires some indication what tab in sync.

**Comment by Semro** [comment]
After #50 changing tab's URL without reloading shouldn't interrupt syncing.
If you go to other URL in syncing tab, then syncing would be stopped, because we don't want to give access to control other site, that not been shared.
