### ISSUE TITLE
Permanently Desync'd

### ISSUE THREAD

**Issue by VashtaxNerada** [Semro/syncwatch#57]
My friend and I were watching a video in Sync Watch and he has another extension called SponsorBlock which will jump him forawrd in a video past a video's sponsorship segment (in-video, not a youtube ad) and when it did so Sync Watch did not jump ahead to the same time and we were permanently desync'd. We tried uninstalling, restarting the video, moving to a different room in the syncwatch, he even removed sponsorblock, nothing helped, so we thought rebooting the computer might work but i have tried to watch videos with others now who do not have any conflicting extensions and i am seemingly permanently roughly 2 minutes behind wherever they are in a video, i am just at a loss for what to do at this point, hope something can be done because i've frequently used and enjoyed this extension. Thanks in advance

Edit: We figured out that it's because of Youtube's new server side ad-injection which seems to technically add the ad's runtime to the video runtime so if i get a 15 second ad and my adblocker blocks it, it treats it as jumping ahead 15 seconds in the video for the other person/people in the sync watch. not sure if that helps or you'd be able to do anything about it, but thought it important information to add

**Comment by Semro** [comment]
Hi! I've tried SponsorBlock extension with SyncWatch (tested on: https://www.youtube.com/watch?v=1rb3bMvDdX4)
It skips sponsored section for everyone in the room.
It will not skip if other user in the room without that extension will seek into sponsored timing, but still videos will stay in sync for everyone, so I don't see a problem here.
