### ISSUE TITLE
How to make Sync Watch open in Chrome Incognito?

### ISSUE THREAD

**Issue by CanYouJustWorkPlease** [Semro/syncwatch#9]
Hi there,

I tried opening a video link within Sync Watch within Chrome Incognito mode, but as I clicked it, it opened the video in Chrome normal mode. So, I came up with a solution to overcome this problem, as such, I added to manifest.json the following:

 "incognito": "split"

Now manifest.json looks like this and it allows links to be opened in Incognito mode, only if Sync Watch is allowed to run in Incognito:

{
"update_url": "https://clients2.google.com/service/update2/crx",

  "manifest_version": 2,
  "name": "__MSG_appName__",
  "description": "__MSG_appDesc__",
  "version": "0.324",
  "default_locale": "en",
  "options_ui": {
    "page": "options.html",
    "open_in_tab": false
  },
  "background": {
    "persistent": true,
    "scripts": ["js/socket.io.slim.js", "js/background.js"]
  },
  "icons": {
    "16": "icons/icon16.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  },
  "browser_action": {
    "default_icon": "icons/icon128.png",
    "default_title": "SyncWatch",
    "default_popup": "popup.html"
  },
  "incognito": "split",
  "permissions": ["<all_urls>", "tabs", "storage", "notifications"]
}

I hope you can push this to the next update of the extension.

Have a nice day!

**Comment by Semro** [comment]
Added incognito support. It's working fine in Chrome and Opera, but unfortunately not supported in Firefox.
